name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@5ff54383dc6676f79163dab1dc4cb7c29f7cd8de # main
    with:
      runner: ubuntu-latest
    secrets: inherit
