name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@d4e229f4fd57b20a53016514e61e3bf9e53dfc7e # main
    with:
      runner: ubuntu-latest
    secrets: inherit
