name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@c2ba2d8915572bebd539fa5ba7ec4219bfc02f18 # main
    with:
      runner: ubuntu-latest
    secrets: inherit
